# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26cb879439e93aaaac8571d826f2ba03f805147233663978ee9dcd57a102884cec2a2434c9c1cdd556800043427967151378a5ac2e9c7581600c805d131e9c47

test:
  secret_key_base: 130410ecbd0a99c57d2966bdc8825403df8e95c44403a6355b68425af5f98f2934b3d537eadd8c2b9d74240425a36551261c3c682959fc2f7f572dbebd833aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
